name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master  # Adjusted to trigger on pushes to master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: cyberrrnaut/cameo:latest

    - name: Verify Pushed Image
      run: docker pull cyberrrnaut/cameo:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}  # Assuming you have this secret too
        username: ${{ secrets.SSH_USERNAME }}  # Assuming you have this secret too
        key: ${{ secrets.SSH_KEY }}  # Assuming you have this secret too
        script: |
          sudo docker pull cyberrrnaut/cameo:latest
          sudo docker stop cameo || true
          sudo docker rm cameo || true
          sudo docker run -d --name cameo -p 8080:3000 \
            -e NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }} \
            -e NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }} \
            -e NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }} \
            -e NEXT_PUBLIC_CLERK_SIGN_UP_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }} \
            -e NEXT_PUBLIC_STREAM_API_KEY=${{ secrets.NEXT_PUBLIC_STREAM_API_KEY }} \
            -e STREAM_SECRET_KEY=${{ secrets.STREAM_SECRET_KEY }} \
            cyberrrnaut/cameo:latest
